export const FILTER_MOVIES = 'FILTER_MOVIES';
export const LOAD_MOVIES = 'LOAD_MOVIES';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_RATING_LIST = 'UPDATE_RATING_LIST';
export const UPDATE_GENRE_LIST = 'UPDATE_GENRE_LIST';